### ISSUE TITLE
support custom excludes/includes rules

### ISSUE THREAD

**Issue by zheeeng** [viteland/vite-plugin-macro#15]
I'm using decorator in my project and enabled `@vitejs/plugin-react-refresh`, it seems can handle decorator by this commit:

https://github.com/vitejs/vite/commit/565bcb4121e678310c26bb249b119da504d13ada

But macro plugin reports syntax error:

![image](https://user-images.githubusercontent.com/1303154/132143386-9fc7d3b5-7209-4204-8407-de557da09146.png)

my vite config:

```ts
import { defineConfig } from "vite";
import reactRefresh from "@vitejs/plugin-react-refresh";
import { defineMacroPlugin } from "vite-plugin-macro";
import { join } from "path";
import { loadConfigMacro } from "./macros/loadConfig";
import { loadPluginsMacro } from "./macros/loadPlugins";
import { loadModulesMacro } from "./macros/loadModules";

export default defineConfig({
  plugins: [
    reactRefresh(),
    defineMacroPlugin({
      name: "macro-plugin",
      typesPath: join(__dirname, "./macros.d.ts"),
      exports: {
        "@loadConfig": {
          macros: [loadConfigMacro],
        },
        "@loadPlugins": {
          macros: [loadPluginsMacro],
        },
        "@loadModules": {
          macros: [loadModulesMacro],
        },
      },
    }),
  ],
});
```

**Comment by unbyte** [comment]
use option `parserPlugins: ['decorators']` in `defineMacroPlugin`

**Comment by unbyte** [comment]
There are lots of comments in the .dts file of the plugin, you can use these comments to understand options/concepts before the new document is created.
![image](https://user-images.githubusercontent.com/5772358/132146070-811a3aaf-a1a7-421d-b7a1-161a0dcee391.png)

**Comment by zheeeng** [comment]
I solved this by parserPlugins option just then. Thx very much for your reply quickly.

**Comment by zheeeng** [comment]
@unbyte I debugged @vitejs/plugin-react-refresh and passed the same parserPlugins option to macro plugin but there are still some syntax parsing error. I'm using a lot of inversify features.

```ts
export default defineConfig({
  plugins: [
    reactRefresh(),
    defineMacroPlugin({
      name: "macro-plugin",
      typesPath: join(__dirname, "./macros.d.ts"),
      parserPlugins: [
        'jsx',
        'importMeta',
        'topLevelAwait',
        'classProperties',
        'classPrivateProperties',
        'classPrivateMethods',
        'typescript',
        'decorators-legacy'
      ],
      exports: {
        "@loadConfig": {
          macros: [loadConfigMacro],
        },
        "@loadPlugins": {
          macros: [loadPluginsMacro],
        },
        "@loadModules": {
          macros: [loadModulesMacro],
        },
      },
    }),
  ],
});

```


![image](https://user-images.githubusercontent.com/1303154/132149075-b7a48561-6e60-4fa0-b1dd-4cb7547f79b4.png)

![image](https://user-images.githubusercontent.com/1303154/132149100-ef4e543c-b2bd-41f1-acd8-b0bb212102c1.png)

![image](https://user-images.githubusercontent.com/1303154/132149121-4fc40189-39d6-4b36-bf12-6c207ada1274.png)

![image](https://user-images.githubusercontent.com/1303154/132149137-8fc90603-d892-460f-a0ea-8b2f3ed7009f.png)

**Comment by zheeeng** [comment]
@unbyte Can we just parse the specific file. I just use Macro in limit scope.

**Comment by unbyte** [comment]
since parser plugin `jsx` is enabled by default, `<Type>xxx` is ambiguous, try `xxx as Type` instead.

**Comment by unbyte** [comment]
> @unbyte Can we just parse the specific file. I just use Macro in limit scope.

include/exclude will be available in the next version.

**Comment by zheeeng** [comment]
> since parser plugin `jsx` is enabled by default, `<Type>xxx` is ambiguous, try `xxx as Type` instead.

I'm migrating a huge legacy project to vite and use Macro to replace prepare script. Modifying the code writing style needs efforts. I gonna try some format tools for this.
