### ISSUE TITLE
Can we have a new plugin for modify import statment?

### ISSUE THREAD

**Issue by zheeeng** [viteland/vite-plugin-macro#24]
As the title says, maybe not provided by the vite-plugin-macro, but a new plugin. Allow us to do a Macro way to modify the import statement.

Like that [rollup-plugin-import](https://www.npmjs.com/package/rollup-plugin-import) does.

**Comment by unbyte** [comment]
One plugin for one task; this plugin is aimed to provide function-like macros. 
Maybe [vite-plugin-imp](https://www.npmjs.com/package/vite-plugin-imp) meets your needs, I use it to rewrite the import statements of antd.
